-- ---------------------------------------------------------------------------
-- ASM Shop Manager — schema
--
-- Money is DECIMAL, never FLOAT: binary floating point cannot represent 0.10
-- exactly, and rounding drift is unacceptable in a ledger.
--
-- Dates are DATE and times are TIME. The app currently carries a display
-- string like "9:14 AM"; that is formatted on read rather than stored.
--
-- Primary keys are CHAR(36) UUIDs generated by the app, so a new row can be
-- rendered optimistically without waiting for a server-assigned id.
-- ---------------------------------------------------------------------------

SET NAMES utf8mb4;

-- ---------------------------------------------------------------------------
-- Sales
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bills (
  id            CHAR(36)      NOT NULL,
  sold_on       DATE          NOT NULL,
  sold_at       TIME          NOT NULL,
  description   VARCHAR(255)  NOT NULL DEFAULT 'Sale',
  category      ENUM('groceries','produce','other') NOT NULL DEFAULT 'other',
  amount        DECIMAL(12,2) NOT NULL,
  mode          ENUM('cash','upi','credit')         NOT NULL DEFAULT 'cash',
  -- Only set when mode = 'credit'; the constraint below enforces that pairing.
  customer      VARCHAR(120)  NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_bills_sold_on (sold_on),
  KEY idx_bills_mode_date (mode, sold_on),
  -- Grouping the credit page by person leans on this one.
  KEY idx_bills_customer (customer, sold_on),
  CONSTRAINT chk_bills_amount CHECK (amount > 0),
  CONSTRAINT chk_bills_customer CHECK (
    (mode = 'credit' AND customer IS NOT NULL AND customer <> '')
    OR (mode <> 'credit' AND customer IS NULL)
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- What a credit customer has paid back, instalment by instalment.
CREATE TABLE IF NOT EXISTS bill_credit_payments (
  id            CHAR(36)      NOT NULL,
  bill_id       CHAR(36)      NOT NULL,
  paid_on       DATE          NOT NULL,
  amount        DECIMAL(12,2) NOT NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_bcp_bill (bill_id, paid_on),
  CONSTRAINT fk_bcp_bill FOREIGN KEY (bill_id) REFERENCES bills (id) ON DELETE CASCADE,
  CONSTRAINT chk_bcp_amount CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Shop expenses
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS expenses (
  id            CHAR(36)      NOT NULL,
  -- The app has no date field for expenses yet, so every one is implicitly
  -- today. Storing a real date is what lets expense history and the profit
  -- figure survive midnight.
  spent_on      DATE          NOT NULL,
  spent_at      TIME          NOT NULL,
  description   VARCHAR(255)  NOT NULL DEFAULT 'Expense',
  category      ENUM('supplier','rent','electricity','wages','transport','other')
                              NOT NULL DEFAULT 'other',
  amount        DECIMAL(12,2) NOT NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_expenses_spent_on (spent_on),
  KEY idx_expenses_category (category, spent_on),
  CONSTRAINT chk_expenses_amount CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Wholesale purchases
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS purchases (
  id            CHAR(36)      NOT NULL,
  bought_on     DATE          NOT NULL,
  supplier      VARCHAR(120)  NOT NULL,
  item          VARCHAR(255)  NOT NULL DEFAULT 'Stock',
  -- Value of the goods taken.
  amount        DECIMAL(12,2) NOT NULL,
  -- Handed over at the counter on the day; later instalments live in
  -- purchase_payments, so this never absorbs them.
  paid_upfront  DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_purchases_bought_on (bought_on),
  -- The Stock tab groups history by shop, most recent first.
  KEY idx_purchases_supplier (supplier, bought_on),
  CONSTRAINT chk_purchases_amount CHECK (amount > 0),
  -- Mirrors the app's guard: the upfront payment can never exceed the goods.
  CONSTRAINT chk_purchases_paid CHECK (paid_upfront >= 0 AND paid_upfront <= amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Money handed to the supplier after the purchase day.
CREATE TABLE IF NOT EXISTS purchase_payments (
  id            CHAR(36)      NOT NULL,
  purchase_id   CHAR(36)      NOT NULL,
  paid_on       DATE          NOT NULL,
  amount        DECIMAL(12,2) NOT NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_pp_purchase (purchase_id, paid_on),
  CONSTRAINT fk_pp_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id) ON DELETE CASCADE,
  CONSTRAINT chk_pp_amount CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Views the app's derived figures map onto directly
-- ---------------------------------------------------------------------------

-- One row per credit sale with what is still to collect.
CREATE OR REPLACE VIEW credit_balances AS
SELECT
  b.id,
  b.customer,
  b.sold_on,
  b.amount,
  COALESCE(SUM(p.amount), 0)                        AS repaid,
  GREATEST(b.amount - COALESCE(SUM(p.amount), 0), 0) AS balance
FROM bills b
LEFT JOIN bill_credit_payments p ON p.bill_id = b.id
WHERE b.mode = 'credit'
GROUP BY b.id, b.customer, b.sold_on, b.amount;

-- One row per wholesale load with what is still owed on it.
CREATE OR REPLACE VIEW purchase_balances AS
SELECT
  w.id,
  w.supplier,
  w.bought_on,
  w.amount,
  w.paid_upfront + COALESCE(SUM(p.amount), 0)                            AS paid,
  GREATEST(w.amount - w.paid_upfront - COALESCE(SUM(p.amount), 0), 0)    AS balance
FROM purchases w
LEFT JOIN purchase_payments p ON p.purchase_id = w.id
GROUP BY w.id, w.supplier, w.bought_on, w.amount, w.paid_upfront;
